### ISSUE TITLE
Couldn't resolving domain twice lead to bypass?

### ISSUE THREAD

**Issue by makindotcc** [nethunterslabs/http-acl#19]
Isn't it possible that domain resolved here will be legitimate
https://github.com/nethunterslabs/http-acl/blob/e556cad0ab5f87598a9efa65d478cddc8741094f/http-acl-reqwest/src/lib.rs#L88-L91

but when resolved once again in reqwest it could resolve to other, blacklisted address?

**Comment by makindotcc** [comment]
It could lead to bypass when someone provides custom [dns_resolver](https://docs.rs/reqwest/0.12.4/reqwest/struct.ClientBuilder.html#method.dns_resolver).

**Comment by veeshi** [comment]
> Isn't it possible that domain resolved here will be legitimate
> 
> https://github.com/nethunterslabs/http-acl/blob/e556cad0ab5f87598a9efa65d478cddc8741094f/http-acl-reqwest/src/lib.rs#L88-L91
> 
> but when resolved once again in reqwest it could resolve to other, blacklisted address?

Apologies for the late response, that's correct it can be bypassed especially with a low TTL. It was a stopgap solution to resolve twice before implementing a custom DNS resolver.

Thanks for the DNS resolver, I'll get that added in!
